# Generated by Django 5.2.16 on 2026-07-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
