# Generated by Django 5.2.16 on 2026-07-08 00:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='conversation',
            name='pipeline_stage',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('QUALIFIED', 'Qualifié'), ('VISIT', 'Visite Planifiée'), ('NEGOTIATION', 'Négociation'), ('WON', 'Gagné'), ('LOST', 'Perdu')], default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('remind_at', models.DateTimeField()),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='chat.conversation')),
            ],
        ),
    ]
