# Generated by Django 5.2.16 on 2026-07-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_district_propertytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='satisfaction_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
